/*
 * Copyright 2010-2019 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.training.solutions.chapter7;

import au.gov.asd.tac.constellation.graph.ReadableGraph;
import au.gov.asd.tac.constellation.training.solutions.chapter3.PandemicConcept;
import au.gov.asd.tac.constellation.views.JavaFxTopComponent;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Generic Pandemic View Top Component.
 */
@TopComponent.Description(
        preferredID = "GenericPandemicViewTopComponent",
        iconBase = "au/gov/asd/tac/constellation/training/solutions/chapter7/biohazard.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(
        mode = "explorer",
        openAtStartup = false)
@ActionID(
        category = "Window",
        id = "au.gov.asd.tac.constellation.training.solutions.chapter7.GenericPandemicViewTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Views", position = 2200)
    ,
    @ActionReference(path = "Shortcuts", name = "CS-Z")})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GenericPandemicViewAction",
        preferredID = "GenericPandemicViewTopComponent")
@Messages({
    "CTL_GenericPandemicViewAction=Generic Pandemic View",
    "CTL_GenericPandemicViewTopComponent=Generic Pandemic View",
    "HINT_GenericPandemicViewTopComponent=Generic Pandemic View"})
public final class GenericPandemicViewTopComponent extends JavaFxTopComponent<PandemicViewPane> {

    private PandemicViewPane pandemicPane;

    public GenericPandemicViewTopComponent() {
        setName(Bundle.CTL_GenericPandemicViewTopComponent());
        setToolTipText(Bundle.HINT_GenericPandemicViewTopComponent());
        initComponents();

        pandemicPane = new PandemicViewPane();
        initContent();

        addAttributeValueChangeHandler(PandemicConcept.VertexAttribute.OUTBREAK, graph -> {
            final ReadableGraph readableGraph = graph.getReadableGraph();
            try {
                pandemicPane.refresh(readableGraph);
            } finally {
                readableGraph.release();
            }
        });
    }

    @Override
    public void handleComponentOpened() {
        manualUpdate();
    }

    @Override
    protected PandemicViewPane createContent() {
        return pandemicPane;
    }

    @Override
    protected String createStyle() {
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
