/*
 * Copyright 2010-2024 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.training.solutions.chapter7;

import au.gov.asd.tac.constellation.graph.Graph;
import au.gov.asd.tac.constellation.graph.ReadableGraph;
import au.gov.asd.tac.constellation.graph.manager.GraphManager;
import au.gov.asd.tac.constellation.graph.manager.GraphManagerListener;
import au.gov.asd.tac.constellation.graph.monitor.GraphChangeEvent;
import au.gov.asd.tac.constellation.graph.monitor.GraphChangeListener;
import au.gov.asd.tac.constellation.training.solutions.chapter3.PandemicConcept;
import au.gov.asd.tac.constellation.utilities.javafx.JavafxStyleManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Properties;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Pandemic View Top Component.
 */
@ConvertAsProperties(
        dtd = "-//au.gov.asd.tac.constellation.training.chapter7//PandemicView//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "PandemicViewTopComponent",
        iconBase = "au/gov/asd/tac/constellation/training/solutions/chapter7/biohazard.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(
        mode = "explorer",
        openAtStartup = false)
@ActionID(
        category = "Window",
        id = "au.gov.asd.tac.constellation.training.solutions.chapter7.PandemicViewTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Views", position = 2000)
    ,
    @ActionReference(path = "Shortcuts", name = "CS-X")})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PandemicViewAction",
        preferredID = "PandemicViewTopComponent")
@Messages({
    "CTL_PandemicViewAction=Pandemic View",
    "CTL_PandemicViewTopComponent=Pandemic View",
    "HINT_PandemicViewTopComponent=Pandemic View"})
public final class PandemicViewTopComponent extends TopComponent implements GraphManagerListener, GraphChangeListener {

    private Graph currentGraph;
    private long outbreakModificationCounter;

    private JFXPanel container;
    private PandemicViewPane pandemicPane;

    public PandemicViewTopComponent() {
        setName(Bundle.CTL_PandemicViewTopComponent());
        setToolTipText(Bundle.HINT_PandemicViewTopComponent());
        initComponents();

        setLayout(new BorderLayout());
        setPreferredSize(new Dimension(500, 500));

        currentGraph = null;
        outbreakModificationCounter = 0L;

        GraphManager.getDefault().addGraphManagerListener(PandemicViewTopComponent.this);

        container = new JFXPanel();

        Platform.setImplicitExit(false);
        Platform.runLater(() -> {
            pandemicPane = new PandemicViewPane();
            container.setScene(new Scene(pandemicPane));
            container.getScene().getStylesheets().addAll(JavafxStyleManager.getMainStyleSheet());
            add(container, BorderLayout.CENTER);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        GraphManager.getDefault().addGraphManagerListener(this);
        newActiveGraph(GraphManager.getDefault().getActiveGraph());
    }

    @Override
    public void componentClosed() {
        GraphManager.getDefault().removeGraphManagerListener(this);
    }

    @Override
    public void newActiveGraph(final Graph graph) {
        if (currentGraph != graph) {
            if (currentGraph != null) {
                currentGraph.removeGraphChangeListener(this);
                currentGraph = null;
            }
            if (graph != null) {
                currentGraph = graph;
                currentGraph.addGraphChangeListener(this);

                ReadableGraph readableGraph = currentGraph.getReadableGraph();
                try {
                    final int outbreakAttributeId = PandemicConcept.VertexAttribute.OUTBREAK.get(readableGraph);
                    outbreakModificationCounter = readableGraph.getValueModificationCounter(outbreakAttributeId);
                } finally {
                    readableGraph.release();
                }
            }
        }
    }

    @Override
    public void graphOpened(final Graph graph) {
    }

    @Override
    public void graphClosed(final Graph graph) {
    }

    @Override
    public void graphChanged(final GraphChangeEvent event) {
        ReadableGraph readableGraph = currentGraph.getReadableGraph();
        try {
            final int outbreakAttributeId = PandemicConcept.VertexAttribute.OUTBREAK.get(readableGraph);
            final long currentOutbreakModificationCounter = readableGraph.getValueModificationCounter(outbreakAttributeId);
            if (currentOutbreakModificationCounter > outbreakModificationCounter) {
                outbreakModificationCounter = currentOutbreakModificationCounter;
                pandemicPane.refresh(readableGraph);
            }
        } finally {
            readableGraph.release();
        }
    }

    void writeProperties(final Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(final Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
